### PR TITLE
WIP: Fix Python 3.7 wheels

### PR DESCRIPTION
**Pull request by astrofrog**
Work in progress, just experimenting with things for now

### CODE REVIEW

**Comment by bsipocz** [comment]
While we're at it, how do you feel trying to do 3.8 wheels? Too soon?

**Comment by bsipocz** [comment]
(I suppose we can use this: https://github.com/MacPython/numpy-wheels/compare/2ff8f2ccad75...6f28d62ec441 as template, but then for sure we need to stick with np 1.17.3)

**Comment by astrofrog** [comment]
Let's do Python 3.8 in a separate PR - the most urgent is to fix the 3.7 wheels. I decided that the easiest fix for now is to simply use a more recent version of Numpy to actually run the tests - but the bug is still present for Numpy 1.14, so we might still want to consider going ahead with the fix in https://github.com/astropy/astropy/pull/9389

**Comment by bsipocz** [comment]
All green, so I go ahead with this now.

Thank you @astrofrog!

**Pull request merged**
