### PR TITLE
Build v1.3.2

### PR DESCRIPTION
**Pull request by tomkooij**
Build tag v1.3.2

### CODE REVIEW

**Comment by tomkooij** [comment]
pinging @matthew-brett 

Can you please merge this and upload the wheels to PyPI? Thanks!

**Comment by matthew-brett** [comment]
Feel free to merge yourself by the way.

**Comment by matthew-brett** [comment]
I uploaded the wheels, and added some more instructions on uploading.

**Comment by tomkooij** [comment]
Thanks!

**Pull request merged**
