### PR TITLE
Build windows wheels using appveyor

### PR DESCRIPTION
**Pull request by tomkooij**
This is very similar to MacPython/pytables-wheels#2

It builds a wheel in a conda enviroments, installs the wheel in a new env and runs tests.

Fixes astropy/astropy#802

### CODE REVIEW

**Comment by tomkooij** [comment]
@matthew-brett : This looks like a "forgotten" feature. This PR should build windows wheels (as discussed in astropy/astropy#802). Appveyor passes on my fork: https://ci.appveyor.com/project/tomkooij/astropy-wheels

Not sure what's wrong with Travis, but should be unrelated to this PR.

Can you enable appveyor for this repo?

**Comment by matthew-brett** [comment]
Oops!  Thanks - merging now.   Is there an astropy appveyor account, or do you want me to enable this in my account?     Happy to do that if that's better.

**Comment by tomkooij** [comment]
Thanks! Enable this repo in the ~~MacPython~~ matthew-brett appveyor account. That should build windows wheels.

I suggest letting appveyor run at least once: The linked appveyor run is 2 months old.

**Comment by matthew-brett** [comment]
Do you mean the astropy appveyor account?  It seems I have access to that.

**Comment by tomkooij** [comment]
@matthew-brett : Other MacPython repo's such as cython and pytables build from your matthew-brett account on appveyor (and then upload to the scipy wheelhouse).

I'm not what the appveyor astropy account can and cannot access or build.

**Comment by matthew-brett** [comment]
OK - I made a new MacPython appveyor account:

https://ci.appveyor.com/project/MacPython/astropy-wheels/build/1.0.2

Can you send me your email so I can add you?

Test failure from Python 3.6 on current Linux builds (probably will also come up on OSX):

https://travis-ci.org/MacPython/astropy-wheels/jobs/190433603#L618

**Comment by tomkooij** [comment]
@matthew-brett : my github / appveyor email is: tomkooij AT tomkooij DOT nl

I'll look into the python 3.6 failure!

**Comment by matthew-brett** [comment]
I added you.

I see that my attempt at adding a Python 3.6 for Appveyor failed - it appears to be picking up Python 2.7 instead:

https://ci.appveyor.com/project/MacPython/astropy-wheels/build/1.0.2/job/0qnypkwtdhrdafyn#L60

Any ideas what's going on there?

**Comment by tomkooij** [comment]
I don't think Miniconda for python 3.6 is out yet. It is supposed to be released together with Anaconda 4.3 at the end of the month.

**Pull request merged**
